#!/bin/bash
# Studient Pomodoro Timer - Quick Commands

echo "🍅 Studient Pomodoro Timer - Quick Commands"
echo "=========================================="
echo ""
echo "📂 Project Location:"
echo "   /home/joey/Documents/Projects/pomodoro/studient-pomo"
echo ""
echo "🚀 Run Commands:"
echo "   npm run dev          # Start development mode"
echo "   npm run build        # Build for production"
echo "   npm run build:win    # Build Windows installer"
echo "   npm run build:mac    # Build macOS DMG"
echo "   npm run build:linux  # Build Linux package"
echo ""
echo "🔧 Development:"
echo "   npm run lint         # Check code quality"
echo "   npm run format       # Format code"
echo "   npm run typecheck    # Type checking"
echo ""
echo "📚 Documentation:"
echo "   README.md            # Full documentation"
echo "   GETTING_STARTED.md   # Quick start guide"
echo "   PROJECT_SUMMARY.md   # Complete feature list"
echo "   ASSETS.md            # Asset requirements"
echo ""
echo "✨ Features:"
echo "   ✅ 5 Timer Modes (Pomodoro, Short, Micro, Short Break, Long Break)"
echo "   ✅ Task Management with Studient defaults"
echo "   ✅ Session History & CSV Export"
echo "   ✅ Customizable Settings"
echo "   ✅ Beautiful UI with Dynamic Themes"
echo "   ✅ 100% Offline - No Login Required"
echo ""
echo "📦 Tech Stack:"
echo "   - Electron 39 + React 19"
echo "   - TypeScript 5 + Vite 5"
echo "   - Tailwind CSS 3"
echo "   - Lucide Icons"
echo ""
echo "🎯 Quick Start:"
echo "   cd /home/joey/Documents/Projects/pomodoro/studient-pomo"
echo "   npm run dev"
echo ""
echo "=========================================="
